CC:=g++ #for unit test (gcc to g++)
INC_DIR:=../../includes
CFLAGS:=-I$(INC_DIR) -g -Wall # -g : gdb debugger, -Wall : show all warning message
LDFLAGS+=-std=c++11 -lgtest -lpthread #for unit test
OBJS:=1442_Count_Triplets_That_Can_Form_Two_Arrays_of_Equal_XOR.o test_1442.o
EXE:=test_1442

all: $(OBJS)
	$(CC) -o $(EXE) $^ $(LDFLAGS)

%.o: %.c
	$(CC) -c $< $(CFLAGS)

clean:
	rm -rf $(OBJS) $(EXE)